# Generated by Django 2.2.5 on 2019-10-18 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0003_auto_20191018_0604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pro_pic',
            field=models.ImageField(blank=True, upload_to='profile_image/'),
        ),
    ]
