# Generated by Django 2.2.5 on 2019-10-18 10:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0007_auto_20191018_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pro_pic',
            field=models.ImageField(blank=True, height_field='picture_height,', upload_to='images', width_field='picture_width'),
        ),
    ]
