# Generated by Django 2.2.5 on 2019-10-18 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('signin', '0009_auto_20191018_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='pro_pic',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
