# Generated by Django 2.2.5 on 2019-10-01 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aut', models.CharField(max_length=255)),
                ('flatno', models.CharField(max_length=255)),
                ('body', models.TextField()),
            ],
        ),
    ]
