# Generated by Django 2.2.5 on 2019-10-01 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aut', models.CharField(max_length=255)),
                ('cart_items', models.CharField(choices=[('a', 'bread'), ('b', 'water'), ('c', 'milk')], max_length=1)),
            ],
        ),
    ]
