# Generated by Django 2.2.5 on 2019-10-01 09:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0002_item'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='cart_items',
        ),
        migrations.AddField(
            model_name='item',
            name='bread',
            field=models.CharField(choices=[('a', 'yes'), ('b', 'no')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
    ]
