# Generated by Django 2.2.5 on 2019-10-01 09:57

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0003_auto_20191001_0953'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='milk',
            field=models.CharField(choices=[('c', 'yes')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='item',
            name='water',
            field=models.CharField(choices=[('b', 'yes')], default=django.utils.timezone.now, max_length=1),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='bread',
            field=models.CharField(choices=[('a', 'yes')], max_length=1),
        ),
    ]
