# Generated by Django 2.2.5 on 2019-10-01 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0004_auto_20191001_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bread',
            field=models.CharField(blank=True, choices=[('a', 'yes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='milk',
            field=models.CharField(blank=True, choices=[('c', 'yes')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='water',
            field=models.CharField(blank=True, choices=[('b', 'yes')], max_length=1),
        ),
    ]
