# Generated by Django 2.2.5 on 2019-10-04 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0006_post_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bread',
            field=models.CharField(blank=True, choices=[('a', '1 packet'), ('f', '2 packet'), ('g', '3 packet')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='milk',
            field=models.CharField(blank=True, choices=[('c', '1 packet'), ('d', '2 packet'), ('e', '3 packet')], max_length=1),
        ),
        migrations.AlterField(
            model_name='item',
            name='water',
            field=models.CharField(blank=True, choices=[('b', '1 CAN'), ('h', '2 CAN'), ('i', '3 CAN')], max_length=1),
        ),
    ]
