# Generated by Django 2.2.5 on 2019-10-04 10:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0007_auto_20191004_1003'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='rice',
            field=models.CharField(blank=True, choices=[('j', '1 kg'), ('k', '3 kg'), ('l', '5 kg'), ('z', '10 kg')], max_length=1),
        ),
    ]
