# Generated by Django 2.2.5 on 2019-10-08 06:38

from django.db import migrations, models
import django.utils.timezone
import ser.models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0009_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='ordered',
        ),
        migrations.RemoveField(
            model_name='order',
            name='items',
        ),
        migrations.AddField(
            model_name='order',
            name='items',
            field=models.CharField(default=django.utils.timezone.now, max_length=300, verbose_name=ser.models.Item),
            preserve_default=False,
        ),
    ]
