# Generated by Django 2.2.5 on 2019-10-08 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0010_auto_20191008_0638'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='flatno',
            new_name='time',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
    ]
