# Generated by Django 2.2.5 on 2019-10-08 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0011_auto_20191008_0723'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='time',
            new_name='flat_number',
        ),
    ]
