# Generated by Django 2.2.6 on 2019-10-21 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0013_item_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bread',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='milk',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='rice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='water',
            field=models.IntegerField(),
        ),
    ]
