# Generated by Django 2.2.6 on 2019-10-23 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0015_auto_20191023_0906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bread',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='milk',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='rice',
            field=models.IntegerField(max_length=10),
        ),
        migrations.AlterField(
            model_name='item',
            name='water',
            field=models.IntegerField(max_length=10),
        ),
    ]
