# Generated by Django 2.2.6 on 2019-10-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0018_auto_20191024_0443'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='bread',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='milk',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='rice',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='item',
            name='water',
            field=models.IntegerField(),
        ),
    ]
