# Generated by Django 2.2.6 on 2019-10-28 10:45

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ser', '0019_auto_20191024_0447'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='flat_number',
            field=models.CharField(default=3, max_length=30),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='item',
            name='bread',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='milk',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='rice',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='item',
            name='water',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
